name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      # Adjust if your tests read this; harmless if unused.
      BASE_URL: http://127.0.0.1:5002

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run unit tests
        run: pytest tests/unit

      - name: Start Flask app (background)
        run: |
          nohup python app.py > /tmp/app.log 2>&1 &
          echo $! > /tmp/app.pid

      - name: Wait for app to be ready on :5002
        run: |
          python - <<'PY'
          import socket, time, sys
          deadline = time.time() + 60
          while time.time() < deadline:
              s = socket.socket()
              try:
                  s.settimeout(1)
                  s.connect(("127.0.0.1", 5002))
                  s.close()
                  sys.exit(0)
              except Exception:
                  time.sleep(1)
          sys.exit("Server did not start on port 5002 within 60s")
          PY

      - name: Run integration tests
      # if your tests need the BASE_URL env, it's already set above
        run: pytest tests/integration

      - name: Show app log on failure
        if: failure()
        run: |
          echo "==== app.log ===="
          sed -n '1,200p' /tmp/app.log || true